url: https://kaesapps.github.io
baseurl: ./

# Site settings
title: KaeS
email: contact@kaes.fr
description: "KaeS website"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Quentin VUILLIOT
  pic: 1
  position: Co-fondateur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Sylvain VUILLIOT
  pic: 2
  position: Co-fondateur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 2, avenue de la République
  - line: 94600 CHOISY LE ROI

# Build settings
markdown: kramdown
permalink: pretty