# Site settings
title: KaeS
email: contact@kaes.free
description: "Les technologies innovantes au service des petites entreprises"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: KaeS
  location: Localisation
  social: Nous suivre
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: github
    url: http://github.com/kaesapps

# Postal address (add as many lines as necessary)
address:
  - line: 2, avenue de la République
  - line: 94600 CHOISY LE ROI
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
